# Generated by Django 4.0.5 on 2022-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ContactId', models.AutoField(primary_key=True, serialize=False)),
                ('ContactName', models.CharField(max_length=30)),
                ('ContactPhone', models.CharField(max_length=15)),
                ('ContactAddress', models.CharField(max_length=40)),
            ],
        ),
    ]
